on:
  push:

jobs:
  docker-hub:
    runs-on: any
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare multiarch env (qemu)
        uses: docker/setup-qemu-action@v3
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          file: amd64.dockerfile
          push: true
          platforms: linux/amd64
          tags: ronmi/mingo:amd64
      - name: Build arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          file: arm64.dockerfile
          push: true
          platforms: linux/arm64
          tags: ronmi/mingo:arm64
      - name: Build armhf
        uses: docker/build-push-action@v6
        with:
          context: .
          file: armhf.dockerfile
          push: true
          platforms: linux/arm/v7
          tags: ronmi/mingo:armhf
      - name: Create multiarch image
        run: |
          docker buildx imagetools create -t ronmi/mingo ronmi/mingo:amd64 ronmi/mingo:arm64 ronmi/mingo:armhf
          
