on:
  push:

jobs:
  docker-hub:
    runs-on: any
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ronmi/mingo:amd64
          build-args: |
            REPO=http://ftp.tw.debian.org/debian
            ARCH=amd64
      - name: Build arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ronmi/mingo:arm64
          build-args: |
            REPO=http://ftp.tw.debian.org/debian
            ARCH=arm64
      - name: Build armhf
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ronmi/mingo:armhf
          build-args: |
            REPO=http://ftp.tw.debian.org/debian
            ARCH=armhf
      - name: Create multiarch image
        run: |
          docker buildx imagetools create -t ronmi/mingo ronmi/mingo:amd64 ronmi/mingo:arm64 ronmi/mingo:armhf
          
